Frontend
veraison/veraison pull request #30
Opened 2021-03-09 14:53 UTC by setrofim

Add demo frontend.

2021-03-09 15:57 UTC, thomas-fossati requested changes
my computer is going crazy

2021-03-09 15:57 UTC, thomas-fossati commented on plugins/opapolicyengine/main_test.go
> +	}
```suggestion
	require.Nil(err)
```

2021-03-09 15:57 UTC, thomas-fossati commented on plugins/opapolicyengine/main_test.go
> +	}
```suggestion
	require.Nil(err)
```

2021-03-09 15:57 UTC, thomas-fossati commented on plugins/opapolicyengine/main_test.go
> +	}
```suggestion
	require.Nil(err)
```

2021-03-09 15:57 UTC, thomas-fossati commented on plugins/opapolicyengine/main_test.go
> +	}
```suggestion
	err = pe.Init(peParams)
	require.Nil(err)
```

2021-03-09 15:57 UTC, thomas-fossati commented on plugins/opapolicyengine/main_test.go
> +	}
```suggestion
	err = pe.LoadPolicy(policyData)
	require.Nil(err)
```

2021-03-09 15:57 UTC, thomas-fossati commented on plugins/opapolicyengine/main_test.go
> +	require.True(isValid)
These two look more like `assert`s to me

(The idea is to use `require` for test preconditions and `assert` for test assertions.)

2021-03-09 15:57 UTC, thomas-fossati commented on plugins/sqlitepolicy/main_test.go
>  	}
```suggestion
	require.Nil(err)
```

2021-03-09 15:57 UTC, thomas-fossati commented on plugins/sqlitepolicy/main_test.go
>  	if err != nil {
```suggestion
```

2021-03-09 15:57 UTC, thomas-fossati commented on plugins/sqlitepolicy/main_test.go
>  	if err != nil {
same as above

2021-03-09 15:57 UTC, thomas-fossati commented on plugins/sqlitepolicy/main_test.go
>  	if err != nil {
ditto

2021-03-09 15:57 UTC, thomas-fossati commented on frontend/Makefile
> +	go build -o verifier cmd/veraison/main.go
without an explicit dependency on the source, the rule becomes quickly inert
```suggestion
verifier: cmd/veraison/main.go
	go build -o $@ $<
```

2021-03-10 15:48 UTC, setrofim commented on frontend/cmd/veraison/main.go
> +	logger, err := zap.NewDevelopment() // TODO configurable
Done: https://github.com/veraison/veraison/issues/32

2021-03-10 15:54 UTC, setrofim commented
Review feedback addressed.

2021-03-10 17:17 UTC, thomas-fossati approved these changes
LGTM, thanks for addressing my tedious comments!

2021-03-10 23:22 UTC, merged

2021-03-11 09:01 UTC, setrofim commented
> just a curiosity: do we still need the lint annotation now that we use reportProblem?

You're totally right, they're no longer needed. I've removed them.